/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TestReportInput {
    tests: Array<TestCode>;
    patientId: PatientId;
    notes: string;
    doctorName: string;
}
export type TestCode = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Test {
    code: TestCode;
    name: string;
    unit: string;
    sampleType: string;
    referenceRange: string;
    price: bigint;
}
export type BillId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type PatientId = bigint;
export interface DashboardStats {
    totalPatients: bigint;
    pendingReports: bigint;
    reportsToday: bigint;
    totalRevenue: bigint;
}
export interface TestCatalogInput {
    code: string;
    name: string;
    unit: string;
    sampleType: string;
    referenceRange: string;
    price: bigint;
}
export interface TestResult {
    result: string;
    code: TestCode;
    unit: string;
    referenceRange: string;
}
export interface Patient {
    age: bigint;
    name: string;
    address: string;
    gender: Gender;
    phone: string;
}
export type ReportId = bigint;
export interface PatientRecord {
    patient: Patient;
    createdAt: bigint;
    updatedAt: bigint;
}
export interface PatientInput {
    age?: bigint;
    name: string;
    address: string;
    gender?: Gender;
    phone: string;
}
export interface Bill {
    lineItems: Array<BillLineItem>;
    paymentStatus: PaymentStatus;
    gstAmount: bigint;
    totalAmount: bigint;
    timestamp: bigint;
    reportId: ReportId;
}
export interface TestReport {
    status: TestStatus;
    completedAt?: bigint;
    tests: Array<TestCode>;
    patientId: PatientId;
    createdAt: bigint;
    results: Array<TestResult>;
    notes: string;
    doctorName: string;
}
export interface BillLineItem {
    testName: string;
    price: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum PaymentStatus {
    paid = "paid",
    unpaid = "unpaid",
    partial = "partial"
}
export enum TestStatus {
    pending = "pending",
    completed = "completed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPatient(rawData: PatientInput): Promise<PatientId>;
    addTestCatalog(test: TestCatalogInput): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBill(reportId: ReportId, lineItems: Array<BillLineItem>): Promise<BillId>;
    createTestReport(input: TestReportInput): Promise<ReportId>;
    getAllBillsByTimestamp(): Promise<Array<Bill>>;
    getAllPatientsByCreatedAt(): Promise<Array<PatientRecord>>;
    getAllTestCatalog(): Promise<Array<Test>>;
    getAllTestCatalogBySampleType(sampleType: string): Promise<Array<Test>>;
    getBill(billId: BillId): Promise<Bill>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getMostRecentPatients(limit: bigint): Promise<Array<Patient>>;
    getPatient(id: PatientId): Promise<Patient>;
    getPatientReportsByCreatedAt(patientId: PatientId): Promise<Array<TestReport>>;
    getReportsByStatus(status: TestStatus): Promise<Array<TestReport>>;
    getSignature(reportId: ReportId): Promise<ExternalBlob>;
    getTestCatalog(code: TestCode): Promise<Test>;
    getTestReport(reportId: ReportId): Promise<TestReport>;
    getTestReportsByCompletedAt(): Promise<Array<TestReport>>;
    getTestReportsByCreatedAt(): Promise<Array<TestReport>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    storeSignature(reportId: ReportId, signature: ExternalBlob): Promise<void>;
    updatePatient(id: PatientId, rawData: PatientInput): Promise<void>;
    updatePaymentStatus(billId: BillId, status: PaymentStatus): Promise<void>;
    updateTestPrice(code: TestCode, price: bigint): Promise<void>;
    updateTestReportResult(reportId: ReportId, results: Array<TestResult>): Promise<void>;
}
import type { Bill as _Bill, BillLineItem as _BillLineItem, ExternalBlob as _ExternalBlob, Gender as _Gender, Patient as _Patient, PatientId as _PatientId, PatientInput as _PatientInput, PatientRecord as _PatientRecord, PaymentStatus as _PaymentStatus, ReportId as _ReportId, TestCode as _TestCode, TestReport as _TestReport, TestResult as _TestResult, TestStatus as _TestStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPatient(arg0: PatientInput): Promise<PatientId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPatient(to_candid_PatientInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPatient(to_candid_PatientInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTestCatalog(arg0: TestCatalogInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTestCatalog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTestCatalog(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBill(arg0: ReportId, arg1: Array<BillLineItem>): Promise<BillId> {
        if (this.processError) {
            try {
                const result = await this.actor.createBill(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBill(arg0, arg1);
            return result;
        }
    }
    async createTestReport(arg0: TestReportInput): Promise<ReportId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestReport(arg0);
            return result;
        }
    }
    async getAllBillsByTimestamp(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBillsByTimestamp();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBillsByTimestamp();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPatientsByCreatedAt(): Promise<Array<PatientRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatientsByCreatedAt();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatientsByCreatedAt();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTestCatalog(): Promise<Array<Test>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestCatalog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestCatalog();
            return result;
        }
    }
    async getAllTestCatalogBySampleType(arg0: string): Promise<Array<Test>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestCatalogBySampleType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestCatalogBySampleType(arg0);
            return result;
        }
    }
    async getBill(arg0: BillId): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.getBill(arg0);
                return from_candid_Bill_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBill(arg0);
            return from_candid_Bill_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getMostRecentPatients(arg0: bigint): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMostRecentPatients(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMostRecentPatients(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatient(arg0: PatientId): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return from_candid_Patient_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return from_candid_Patient_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientReportsByCreatedAt(arg0: PatientId): Promise<Array<TestReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientReportsByCreatedAt(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientReportsByCreatedAt(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReportsByStatus(arg0: TestStatus): Promise<Array<TestReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByStatus(to_candid_TestStatus_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByStatus(to_candid_TestStatus_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignature(arg0: ReportId): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignature(arg0);
                return from_candid_ExternalBlob_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignature(arg0);
            return from_candid_ExternalBlob_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestCatalog(arg0: TestCode): Promise<Test> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestCatalog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestCatalog(arg0);
            return result;
        }
    }
    async getTestReport(arg0: ReportId): Promise<TestReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestReport(arg0);
                return from_candid_TestReport_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestReport(arg0);
            return from_candid_TestReport_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestReportsByCompletedAt(): Promise<Array<TestReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestReportsByCompletedAt();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestReportsByCompletedAt();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestReportsByCreatedAt(): Promise<Array<TestReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestReportsByCreatedAt();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestReportsByCreatedAt();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async storeSignature(arg0: ReportId, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeSignature(arg0, await to_candid_ExternalBlob_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeSignature(arg0, await to_candid_ExternalBlob_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePatient(arg0: PatientId, arg1: PatientInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, to_candid_PatientInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, to_candid_PatientInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePaymentStatus(arg0: BillId, arg1: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTestPrice(arg0: TestCode, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestPrice(arg0, arg1);
            return result;
        }
    }
    async updateTestReportResult(arg0: ReportId, arg1: Array<TestResult>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestReportResult(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestReportResult(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Bill_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bill): Bill {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_PatientRecord_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientRecord): PatientRecord {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Patient_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TestReport_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestReport): TestReport {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_TestStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestStatus): TestStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lineItems: Array<_BillLineItem>;
    paymentStatus: _PaymentStatus;
    gstAmount: bigint;
    totalAmount: bigint;
    timestamp: bigint;
    reportId: _ReportId;
}): {
    lineItems: Array<BillLineItem>;
    paymentStatus: PaymentStatus;
    gstAmount: bigint;
    totalAmount: bigint;
    timestamp: bigint;
    reportId: ReportId;
} {
    return {
        lineItems: value.lineItems,
        paymentStatus: from_candid_PaymentStatus_n17(_uploadFile, _downloadFile, value.paymentStatus),
        gstAmount: value.gstAmount,
        totalAmount: value.totalAmount,
        timestamp: value.timestamp,
        reportId: value.reportId
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: _Patient;
    createdAt: bigint;
    updatedAt: bigint;
}): {
    patient: Patient;
    createdAt: bigint;
    updatedAt: bigint;
} {
    return {
        patient: from_candid_Patient_n22(_uploadFile, _downloadFile, value.patient),
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    name: string;
    address: string;
    gender: _Gender;
    phone: string;
}): {
    age: bigint;
    name: string;
    address: string;
    gender: Gender;
    phone: string;
} {
    return {
        age: value.age,
        name: value.name,
        address: value.address,
        gender: from_candid_Gender_n24(_uploadFile, _downloadFile, value.gender),
        phone: value.phone
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TestStatus;
    completedAt: [] | [bigint];
    tests: Array<_TestCode>;
    patientId: _PatientId;
    createdAt: bigint;
    results: Array<_TestResult>;
    notes: string;
    doctorName: string;
}): {
    status: TestStatus;
    completedAt?: bigint;
    tests: Array<TestCode>;
    patientId: PatientId;
    createdAt: bigint;
    results: Array<TestResult>;
    notes: string;
    doctorName: string;
} {
    return {
        status: from_candid_TestStatus_n33(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.completedAt)),
        tests: value.tests,
        patientId: value.patientId,
        createdAt: value.createdAt,
        results: value.results,
        notes: value.notes,
        doctorName: value.doctorName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
} | {
    partial: null;
}): PaymentStatus {
    return "paid" in value ? PaymentStatus.paid : "unpaid" in value ? PaymentStatus.unpaid : "partial" in value ? PaymentStatus.partial : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
}): TestStatus {
    return "pending" in value ? TestStatus.pending : "completed" in value ? TestStatus.completed : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bill>): Array<Bill> {
    return value.map((x)=>from_candid_Bill_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PatientRecord>): Array<PatientRecord> {
    return value.map((x)=>from_candid_PatientRecord_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestReport>): Array<TestReport> {
    return value.map((x)=>from_candid_TestReport_n31(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_PatientInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientInput): _PatientInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_TestStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestStatus): _TestStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age?: bigint;
    name: string;
    address: string;
    gender?: Gender;
    phone: string;
}): {
    age: [] | [bigint];
    name: string;
    address: string;
    gender: [] | [_Gender];
    phone: string;
} {
    return {
        age: value.age ? candid_some(value.age) : candid_none(),
        name: value.name,
        address: value.address,
        gender: value.gender ? candid_some(to_candid_Gender_n10(_uploadFile, _downloadFile, value.gender)) : candid_none(),
        phone: value.phone
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TestStatus): {
    pending: null;
} | {
    completed: null;
} {
    return value == TestStatus.pending ? {
        pending: null
    } : value == TestStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    paid: null;
} | {
    unpaid: null;
} | {
    partial: null;
} {
    return value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.unpaid ? {
        unpaid: null
    } : value == PaymentStatus.partial ? {
        partial: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
