export const LAB_INFO = {
  name: "PathLab Pro Diagnostics",
  gstNo: "27AABCP1234A1Z5",
  address: "123 Medical Complex, Health Street, Mumbai - 400001",
  phone: "+91 98765 43210",
  email: "info@pathlabpro.com",
  website: "www.pathlabpro.com",
};

export const GST_RATE = 0.18;
export const CGST_RATE = 0.09;
export const SGST_RATE = 0.09;

export const SAMPLE_TEST_CATALOG = [
  // ── HAEMATOLOGY ──
  {
    code: "CBC",
    name: "Complete Blood Count (CBC)",
    unit: "cells/μL",
    referenceRange: "RBC: 4.5-5.5M | WBC: 4000-11000 | Hb: 12-17 g/dL",
    price: 0n,
    sampleType: "Blood (EDTA)",
  },
  {
    code: "HB",
    name: "Haemoglobin",
    unit: "g/dL",
    referenceRange: "M: 13-17 | F: 12-15",
    price: 0n,
    sampleType: "Blood (EDTA)",
  },
  {
    code: "ESR",
    name: "ESR (Erythrocyte Sedimentation Rate)",
    unit: "mm/hr",
    referenceRange: "M: 0-15 | F: 0-20",
    price: 0n,
    sampleType: "Blood (EDTA)",
  },
  {
    code: "BT-CT",
    name: "Bleeding Time / Clotting Time",
    unit: "min",
    referenceRange: "BT: 1-3 min | CT: 4-10 min",
    price: 0n,
    sampleType: "Blood (Whole)",
  },
  {
    code: "PLT",
    name: "Platelet Count",
    unit: "lakh/μL",
    referenceRange: "1.5-4.5 lakh/μL",
    price: 0n,
    sampleType: "Blood (EDTA)",
  },
  {
    code: "PBS",
    name: "Peripheral Blood Smear",
    unit: "N/A",
    referenceRange: "Normal morphology",
    price: 0n,
    sampleType: "Blood (EDTA)",
  },
  {
    code: "RETIC",
    name: "Reticulocyte Count",
    unit: "%",
    referenceRange: "0.5-1.5%",
    price: 0n,
    sampleType: "Blood (EDTA)",
  },
  {
    code: "BG",
    name: "Blood Group & Rh Factor",
    unit: "N/A",
    referenceRange: "A/B/AB/O, Rh+/-",
    price: 0n,
    sampleType: "Blood (EDTA)",
  },
  {
    code: "PT-INR",
    name: "PT / INR",
    unit: "seconds",
    referenceRange: "11-13.5 sec | INR: 0.9-1.1",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "APTT",
    name: "aPTT",
    unit: "seconds",
    referenceRange: "25-35 seconds",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "MP",
    name: "Malaria Parasite (MP) Test",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Blood (EDTA)",
  },
  {
    code: "MALARIA-AG",
    name: "Malaria Antigen (RDT)",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Blood (Whole)",
  },

  // ── BLOOD SUGAR ──
  {
    code: "GLUCO-F",
    name: "Blood Glucose Fasting",
    unit: "mg/dL",
    referenceRange: "70-100 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "GLUCO-PP",
    name: "Blood Glucose Post Prandial (PP)",
    unit: "mg/dL",
    referenceRange: "<140 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "GLUCO-R",
    name: "Blood Glucose Random",
    unit: "mg/dL",
    referenceRange: "<200 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "HBA1C",
    name: "HbA1c (Glycated Haemoglobin)",
    unit: "%",
    referenceRange: "<5.7% Normal | 5.7-6.4% Pre-diabetic | >6.5% Diabetic",
    price: 0n,
    sampleType: "Blood (EDTA)",
  },
  {
    code: "INSULIN-F",
    name: "Insulin (Fasting)",
    unit: "μIU/mL",
    referenceRange: "2-25 μIU/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "C-PEP",
    name: "C-Peptide",
    unit: "ng/mL",
    referenceRange: "0.9-7.1 ng/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── LIVER FUNCTION ──
  {
    code: "LFT",
    name: "Liver Function Test (LFT)",
    unit: "U/L",
    referenceRange: "SGOT: 10-40 | SGPT: 7-56 | ALP: 44-147",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "SGOT",
    name: "SGOT / AST",
    unit: "U/L",
    referenceRange: "10-40 U/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "SGPT",
    name: "SGPT / ALT",
    unit: "U/L",
    referenceRange: "7-56 U/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "ALP",
    name: "Alkaline Phosphatase (ALP)",
    unit: "U/L",
    referenceRange: "44-147 U/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "GGT",
    name: "Gamma GT (GGT)",
    unit: "U/L",
    referenceRange: "M: 9-48 | F: 5-30 U/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "BILI-T",
    name: "Bilirubin Total",
    unit: "mg/dL",
    referenceRange: "0.2-1.2 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "BILI-D",
    name: "Bilirubin Direct",
    unit: "mg/dL",
    referenceRange: "0-0.3 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "BILI-I",
    name: "Bilirubin Indirect",
    unit: "mg/dL",
    referenceRange: "0.1-0.9 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "TP",
    name: "Total Protein",
    unit: "g/dL",
    referenceRange: "6.3-8.2 g/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "ALB",
    name: "Albumin",
    unit: "g/dL",
    referenceRange: "3.5-5.0 g/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "GLOB",
    name: "Globulin",
    unit: "g/dL",
    referenceRange: "2.0-3.5 g/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── KIDNEY FUNCTION ──
  {
    code: "KFT",
    name: "Kidney Function Test (KFT)",
    unit: "mg/dL",
    referenceRange: "Creatinine: 0.6-1.2 | Urea: 7-20 | eGFR: >60",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "CREAT",
    name: "Serum Creatinine",
    unit: "mg/dL",
    referenceRange: "M: 0.7-1.3 | F: 0.6-1.1 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "BUN",
    name: "Blood Urea Nitrogen (BUN)",
    unit: "mg/dL",
    referenceRange: "7-20 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "UREA",
    name: "Serum Urea",
    unit: "mg/dL",
    referenceRange: "15-45 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "URIC",
    name: "Uric Acid",
    unit: "mg/dL",
    referenceRange: "M: 3.5-7.2 | F: 2.6-6.0 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "EGFR",
    name: "eGFR (Estimated GFR)",
    unit: "mL/min/1.73m²",
    referenceRange: ">60 Normal",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── LIPID PROFILE ──
  {
    code: "LIPID",
    name: "Lipid Profile",
    unit: "mg/dL",
    referenceRange: "Total Chol: <200 | LDL: <100 | HDL: >60 | TG: <150",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "CHOL",
    name: "Total Cholesterol",
    unit: "mg/dL",
    referenceRange: "<200 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "HDL",
    name: "HDL Cholesterol",
    unit: "mg/dL",
    referenceRange: ">60 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "LDL",
    name: "LDL Cholesterol",
    unit: "mg/dL",
    referenceRange: "<100 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "VLDL",
    name: "VLDL Cholesterol",
    unit: "mg/dL",
    referenceRange: "2-30 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "TG",
    name: "Triglycerides",
    unit: "mg/dL",
    referenceRange: "<150 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── THYROID ──
  {
    code: "TFT",
    name: "Thyroid Function Test (TFT)",
    unit: "mIU/L",
    referenceRange: "TSH: 0.4-4.0 | T3: 80-200 ng/dL | T4: 5-12 μg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "TSH",
    name: "TSH (Thyroid Stimulating Hormone)",
    unit: "mIU/L",
    referenceRange: "0.4-4.0 mIU/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "FT3",
    name: "Free T3 (Tri-iodothyronine)",
    unit: "pg/mL",
    referenceRange: "2.0-4.4 pg/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "FT4",
    name: "Free T4 (Thyroxine)",
    unit: "ng/dL",
    referenceRange: "0.8-1.8 ng/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "ANTI-TPO",
    name: "Anti-TPO Antibodies",
    unit: "IU/mL",
    referenceRange: "<35 IU/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "ANTI-TG",
    name: "Anti-Thyroglobulin Antibodies",
    unit: "IU/mL",
    referenceRange: "<115 IU/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── HORMONES ──
  {
    code: "FSH",
    name: "FSH (Follicle Stimulating Hormone)",
    unit: "mIU/mL",
    referenceRange: "F: 3.5-12.5 | M: 1.5-12.4 mIU/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "LH",
    name: "LH (Luteinizing Hormone)",
    unit: "mIU/mL",
    referenceRange: "F: 2.4-12.6 | M: 1.7-8.6 mIU/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "PROLACT",
    name: "Prolactin",
    unit: "ng/mL",
    referenceRange: "F: 2-29 | M: 2-18 ng/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "TEST",
    name: "Testosterone (Total)",
    unit: "ng/dL",
    referenceRange: "M: 300-1000 | F: 15-70 ng/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "E2",
    name: "Estradiol (E2)",
    unit: "pg/mL",
    referenceRange: "F: 20-350 | M: 10-40 pg/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "PROG",
    name: "Progesterone",
    unit: "ng/mL",
    referenceRange: "Follicular: 0.1-0.9 | Luteal: 2-25 ng/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "CORTISOL",
    name: "Cortisol (Morning)",
    unit: "μg/dL",
    referenceRange: "6-23 μg/dL (morning)",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "DHEAS",
    name: "DHEA-S",
    unit: "μg/dL",
    referenceRange: "M: 100-600 | F: 80-420 μg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "BETA-HCG",
    name: "Beta HCG (Pregnancy Test)",
    unit: "mIU/mL",
    referenceRange: "Non-pregnant: <5 mIU/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "PSA",
    name: "PSA (Prostate Specific Antigen)",
    unit: "ng/mL",
    referenceRange: "<4.0 ng/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── VITAMINS & MINERALS ──
  {
    code: "VITD",
    name: "Vitamin D (25-OH)",
    unit: "ng/mL",
    referenceRange: "30-100 ng/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "VITB12",
    name: "Vitamin B12",
    unit: "pg/mL",
    referenceRange: "200-900 pg/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "FOLATE",
    name: "Folic Acid (Folate)",
    unit: "ng/mL",
    referenceRange: ">3.0 ng/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "CA",
    name: "Calcium (Serum)",
    unit: "mg/dL",
    referenceRange: "8.5-10.5 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "PHOS",
    name: "Phosphorus (Serum)",
    unit: "mg/dL",
    referenceRange: "2.5-4.5 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "MG",
    name: "Magnesium (Serum)",
    unit: "mg/dL",
    referenceRange: "1.7-2.2 mg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "ELEC",
    name: "Electrolytes (Na/K/Cl)",
    unit: "mEq/L",
    referenceRange: "Na: 136-145 | K: 3.5-5.0 | Cl: 98-107",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "NA",
    name: "Sodium (Serum)",
    unit: "mEq/L",
    referenceRange: "136-145 mEq/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "K",
    name: "Potassium (Serum)",
    unit: "mEq/L",
    referenceRange: "3.5-5.0 mEq/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "IRON",
    name: "Serum Iron",
    unit: "μg/dL",
    referenceRange: "M: 60-170 | F: 50-170 μg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "TIBC",
    name: "TIBC (Total Iron Binding Capacity)",
    unit: "μg/dL",
    referenceRange: "250-370 μg/dL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "FERR",
    name: "Ferritin",
    unit: "ng/mL",
    referenceRange: "M: 12-300 | F: 12-150 ng/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── CARDIAC MARKERS ──
  {
    code: "TROP-I",
    name: "Troponin I",
    unit: "ng/mL",
    referenceRange: "<0.04 ng/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "TROP-T",
    name: "Troponin T",
    unit: "ng/mL",
    referenceRange: "<0.1 ng/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "CKMB",
    name: "CK-MB",
    unit: "U/L",
    referenceRange: "<25 U/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "CPK",
    name: "CPK (Creatine Phosphokinase)",
    unit: "U/L",
    referenceRange: "M: 38-174 | F: 26-140 U/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "LDH",
    name: "LDH (Lactate Dehydrogenase)",
    unit: "U/L",
    referenceRange: "140-280 U/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── INFLAMMATION / IMMUNOLOGY ──
  {
    code: "CRP",
    name: "CRP (C-Reactive Protein)",
    unit: "mg/L",
    referenceRange: "<5 mg/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "HS-CRP",
    name: "hs-CRP (High Sensitivity CRP)",
    unit: "mg/L",
    referenceRange: "<1.0 mg/L (low risk)",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "RA",
    name: "RA Factor (Rheumatoid Arthritis)",
    unit: "IU/mL",
    referenceRange: "<14 IU/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "ASO",
    name: "ASO Titre",
    unit: "IU/mL",
    referenceRange: "<200 IU/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "ANA",
    name: "ANA (Anti-Nuclear Antibody)",
    unit: "Titer",
    referenceRange: "Negative (<1:40)",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "ANTI-DS",
    name: "Anti-dsDNA",
    unit: "IU/mL",
    referenceRange: "<30 IU/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "PROCALC",
    name: "Procalcitonin",
    unit: "ng/mL",
    referenceRange: "<0.5 ng/mL",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── SEROLOGY / INFECTION ──
  {
    code: "WIDAL",
    name: "Widal Test (Typhoid)",
    unit: "Titer",
    referenceRange: "<1:80",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "TYPHI-DOT",
    name: "Typhidot / Typhoid IgM/IgG",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "DENGUE-NS1",
    name: "Dengue NS1 Antigen",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "DENGUE-IGM",
    name: "Dengue IgM / IgG",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "HIV",
    name: "HIV 1 & 2 (ELISA)",
    unit: "N/A",
    referenceRange: "Non-Reactive",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "HBSAG",
    name: "HBsAg (Hepatitis B Surface Antigen)",
    unit: "N/A",
    referenceRange: "Non-Reactive",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "ANTI-HCV",
    name: "Anti-HCV (Hepatitis C)",
    unit: "N/A",
    referenceRange: "Non-Reactive",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "VDRL",
    name: "VDRL (Syphilis)",
    unit: "Titer",
    referenceRange: "Non-Reactive",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "COVID-AG",
    name: "COVID-19 Antigen Test",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Swab",
  },
  {
    code: "COVID-AB",
    name: "COVID-19 IgM/IgG Antibody",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── PANCREAS ──
  {
    code: "AMYL",
    name: "Amylase (Serum)",
    unit: "U/L",
    referenceRange: "28-100 U/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },
  {
    code: "LIPASE",
    name: "Lipase (Serum)",
    unit: "U/L",
    referenceRange: "10-73 U/L",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── URINE TESTS ──
  {
    code: "URINE-R",
    name: "Urine Routine & Microscopy",
    unit: "N/A",
    referenceRange: "pH: 4.5-8.0 | Protein: Neg | Glucose: Neg",
    price: 0n,
    sampleType: "Urine",
  },
  {
    code: "URINE-CS",
    name: "Urine Culture & Sensitivity",
    unit: "N/A",
    referenceRange: "No growth",
    price: 0n,
    sampleType: "Urine",
  },
  {
    code: "MICRO-ALB",
    name: "Urine Microalbumin",
    unit: "mg/L",
    referenceRange: "<30 mg/L",
    price: 0n,
    sampleType: "Urine",
  },
  {
    code: "URINE-CREAT",
    name: "Urine Creatinine",
    unit: "mg/dL",
    referenceRange: "M: 14-26 | F: 11-20 mg/kg/day",
    price: 0n,
    sampleType: "Urine",
  },
  {
    code: "URINE-PROT",
    name: "24-Hr Urine Protein",
    unit: "mg/24hr",
    referenceRange: "<150 mg/24hr",
    price: 0n,
    sampleType: "Urine",
  },
  {
    code: "PREGTEST",
    name: "Urine Pregnancy Test (UPT)",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Urine",
  },

  // ── STOOL TESTS ──
  {
    code: "STOOL-R",
    name: "Stool Routine & Microscopy",
    unit: "N/A",
    referenceRange: "Normal",
    price: 0n,
    sampleType: "Stool",
  },
  {
    code: "STOOL-CS",
    name: "Stool Culture & Sensitivity",
    unit: "N/A",
    referenceRange: "No pathogen",
    price: 0n,
    sampleType: "Stool",
  },
  {
    code: "OCCULT",
    name: "Occult Blood (Stool)",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Stool",
  },
  {
    code: "H-PYLORI-SA",
    name: "H. Pylori Stool Antigen",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Stool",
  },
  {
    code: "H-PYLORI-AB",
    name: "H. Pylori IgG (Blood)",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Blood (Serum)",
  },

  // ── MICROBIOLOGY / CULTURES ──
  {
    code: "BLOOD-CS",
    name: "Blood Culture & Sensitivity",
    unit: "N/A",
    referenceRange: "No growth",
    price: 0n,
    sampleType: "Blood (Whole)",
  },
  {
    code: "SPUTUM-CS",
    name: "Sputum Culture & Sensitivity",
    unit: "N/A",
    referenceRange: "No growth",
    price: 0n,
    sampleType: "Sputum",
  },
  {
    code: "SPUTUM-AFB",
    name: "Sputum AFB (TB Smear)",
    unit: "N/A",
    referenceRange: "Negative",
    price: 0n,
    sampleType: "Sputum",
  },
  {
    code: "SWAB-CS",
    name: "Throat / Wound Swab Culture",
    unit: "N/A",
    referenceRange: "No growth",
    price: 0n,
    sampleType: "Swab",
  },
];
