/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'lineItems' : Array<BillLineItem>,
  'paymentStatus' : PaymentStatus,
  'gstAmount' : bigint,
  'totalAmount' : bigint,
  'timestamp' : bigint,
  'reportId' : ReportId,
}
export type BillId = bigint;
export interface BillLineItem { 'testName' : string, 'price' : bigint }
export interface DashboardStats {
  'totalPatients' : bigint,
  'pendingReports' : bigint,
  'reportsToday' : bigint,
  'totalRevenue' : bigint,
}
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface Patient {
  'age' : bigint,
  'name' : string,
  'address' : string,
  'gender' : Gender,
  'phone' : string,
}
export type PatientId = bigint;
export interface PatientInput {
  'age' : [] | [bigint],
  'name' : string,
  'address' : string,
  'gender' : [] | [Gender],
  'phone' : string,
}
export interface PatientRecord {
  'patient' : Patient,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export type PaymentStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'partial' : null };
export type ReportId = bigint;
export interface Test {
  'code' : TestCode,
  'name' : string,
  'unit' : string,
  'sampleType' : string,
  'referenceRange' : string,
  'price' : bigint,
}
export interface TestCatalogInput {
  'code' : string,
  'name' : string,
  'unit' : string,
  'sampleType' : string,
  'referenceRange' : string,
  'price' : bigint,
}
export type TestCode = string;
export interface TestReport {
  'status' : TestStatus,
  'completedAt' : [] | [bigint],
  'tests' : Array<TestCode>,
  'patientId' : PatientId,
  'createdAt' : bigint,
  'results' : Array<TestResult>,
  'notes' : string,
  'doctorName' : string,
}
export interface TestReportInput {
  'tests' : Array<TestCode>,
  'patientId' : PatientId,
  'notes' : string,
  'doctorName' : string,
}
export interface TestResult {
  'result' : string,
  'code' : TestCode,
  'unit' : string,
  'referenceRange' : string,
}
export type TestStatus = { 'pending' : null } |
  { 'completed' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPatient' : ActorMethod<[PatientInput], PatientId>,
  'addTestCatalog' : ActorMethod<[TestCatalogInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBill' : ActorMethod<[ReportId, Array<BillLineItem>], BillId>,
  'createTestReport' : ActorMethod<[TestReportInput], ReportId>,
  'getAllBillsByTimestamp' : ActorMethod<[], Array<Bill>>,
  'getAllPatientsByCreatedAt' : ActorMethod<[], Array<PatientRecord>>,
  'getAllTestCatalog' : ActorMethod<[], Array<Test>>,
  'getAllTestCatalogBySampleType' : ActorMethod<[string], Array<Test>>,
  'getBill' : ActorMethod<[BillId], Bill>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMostRecentPatients' : ActorMethod<[bigint], Array<Patient>>,
  'getPatient' : ActorMethod<[PatientId], Patient>,
  'getPatientReportsByCreatedAt' : ActorMethod<[PatientId], Array<TestReport>>,
  'getReportsByStatus' : ActorMethod<[TestStatus], Array<TestReport>>,
  'getSignature' : ActorMethod<[ReportId], ExternalBlob>,
  'getTestCatalog' : ActorMethod<[TestCode], Test>,
  'getTestReport' : ActorMethod<[ReportId], TestReport>,
  'getTestReportsByCompletedAt' : ActorMethod<[], Array<TestReport>>,
  'getTestReportsByCreatedAt' : ActorMethod<[], Array<TestReport>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'storeSignature' : ActorMethod<[ReportId, ExternalBlob], undefined>,
  'updatePatient' : ActorMethod<[PatientId, PatientInput], undefined>,
  'updatePaymentStatus' : ActorMethod<[BillId, PaymentStatus], undefined>,
  'updateTestPrice' : ActorMethod<[TestCode, bigint], undefined>,
  'updateTestReportResult' : ActorMethod<
    [ReportId, Array<TestResult>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
