/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const PatientInput = IDL.Record({
  'age' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'address' : IDL.Text,
  'gender' : IDL.Opt(Gender),
  'phone' : IDL.Text,
});
export const PatientId = IDL.Nat;
export const TestCatalogInput = IDL.Record({
  'code' : IDL.Text,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'sampleType' : IDL.Text,
  'referenceRange' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReportId = IDL.Nat;
export const BillLineItem = IDL.Record({
  'testName' : IDL.Text,
  'price' : IDL.Nat,
});
export const BillId = IDL.Nat;
export const TestCode = IDL.Text;
export const TestReportInput = IDL.Record({
  'tests' : IDL.Vec(TestCode),
  'patientId' : PatientId,
  'notes' : IDL.Text,
  'doctorName' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
  'partial' : IDL.Null,
});
export const Bill = IDL.Record({
  'lineItems' : IDL.Vec(BillLineItem),
  'paymentStatus' : PaymentStatus,
  'gstAmount' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'reportId' : ReportId,
});
export const Patient = IDL.Record({
  'age' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'gender' : Gender,
  'phone' : IDL.Text,
});
export const PatientRecord = IDL.Record({
  'patient' : Patient,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const Test = IDL.Record({
  'code' : TestCode,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'sampleType' : IDL.Text,
  'referenceRange' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalPatients' : IDL.Nat,
  'pendingReports' : IDL.Nat,
  'reportsToday' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const TestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const TestResult = IDL.Record({
  'result' : IDL.Text,
  'code' : TestCode,
  'unit' : IDL.Text,
  'referenceRange' : IDL.Text,
});
export const TestReport = IDL.Record({
  'status' : TestStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'tests' : IDL.Vec(TestCode),
  'patientId' : PatientId,
  'createdAt' : IDL.Int,
  'results' : IDL.Vec(TestResult),
  'notes' : IDL.Text,
  'doctorName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPatient' : IDL.Func([PatientInput], [PatientId], []),
  'addTestCatalog' : IDL.Func([TestCatalogInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBill' : IDL.Func([ReportId, IDL.Vec(BillLineItem)], [BillId], []),
  'createTestReport' : IDL.Func([TestReportInput], [ReportId], []),
  'getAllBillsByTimestamp' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getAllPatientsByCreatedAt' : IDL.Func(
      [],
      [IDL.Vec(PatientRecord)],
      ['query'],
    ),
  'getAllTestCatalog' : IDL.Func([], [IDL.Vec(Test)], ['query']),
  'getAllTestCatalogBySampleType' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Test)],
      ['query'],
    ),
  'getBill' : IDL.Func([BillId], [Bill], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMostRecentPatients' : IDL.Func([IDL.Nat], [IDL.Vec(Patient)], ['query']),
  'getPatient' : IDL.Func([PatientId], [Patient], ['query']),
  'getPatientReportsByCreatedAt' : IDL.Func(
      [PatientId],
      [IDL.Vec(TestReport)],
      ['query'],
    ),
  'getReportsByStatus' : IDL.Func(
      [TestStatus],
      [IDL.Vec(TestReport)],
      ['query'],
    ),
  'getSignature' : IDL.Func([ReportId], [ExternalBlob], ['query']),
  'getTestCatalog' : IDL.Func([TestCode], [Test], ['query']),
  'getTestReport' : IDL.Func([ReportId], [TestReport], ['query']),
  'getTestReportsByCompletedAt' : IDL.Func(
      [],
      [IDL.Vec(TestReport)],
      ['query'],
    ),
  'getTestReportsByCreatedAt' : IDL.Func([], [IDL.Vec(TestReport)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'storeSignature' : IDL.Func([ReportId, ExternalBlob], [], []),
  'updatePatient' : IDL.Func([PatientId, PatientInput], [], []),
  'updatePaymentStatus' : IDL.Func([BillId, PaymentStatus], [], []),
  'updateTestPrice' : IDL.Func([TestCode, IDL.Nat], [], []),
  'updateTestReportResult' : IDL.Func([ReportId, IDL.Vec(TestResult)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const PatientInput = IDL.Record({
    'age' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'address' : IDL.Text,
    'gender' : IDL.Opt(Gender),
    'phone' : IDL.Text,
  });
  const PatientId = IDL.Nat;
  const TestCatalogInput = IDL.Record({
    'code' : IDL.Text,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'sampleType' : IDL.Text,
    'referenceRange' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReportId = IDL.Nat;
  const BillLineItem = IDL.Record({ 'testName' : IDL.Text, 'price' : IDL.Nat });
  const BillId = IDL.Nat;
  const TestCode = IDL.Text;
  const TestReportInput = IDL.Record({
    'tests' : IDL.Vec(TestCode),
    'patientId' : PatientId,
    'notes' : IDL.Text,
    'doctorName' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'paid' : IDL.Null,
    'unpaid' : IDL.Null,
    'partial' : IDL.Null,
  });
  const Bill = IDL.Record({
    'lineItems' : IDL.Vec(BillLineItem),
    'paymentStatus' : PaymentStatus,
    'gstAmount' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'reportId' : ReportId,
  });
  const Patient = IDL.Record({
    'age' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'gender' : Gender,
    'phone' : IDL.Text,
  });
  const PatientRecord = IDL.Record({
    'patient' : Patient,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const Test = IDL.Record({
    'code' : TestCode,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'sampleType' : IDL.Text,
    'referenceRange' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalPatients' : IDL.Nat,
    'pendingReports' : IDL.Nat,
    'reportsToday' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const TestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const TestResult = IDL.Record({
    'result' : IDL.Text,
    'code' : TestCode,
    'unit' : IDL.Text,
    'referenceRange' : IDL.Text,
  });
  const TestReport = IDL.Record({
    'status' : TestStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'tests' : IDL.Vec(TestCode),
    'patientId' : PatientId,
    'createdAt' : IDL.Int,
    'results' : IDL.Vec(TestResult),
    'notes' : IDL.Text,
    'doctorName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPatient' : IDL.Func([PatientInput], [PatientId], []),
    'addTestCatalog' : IDL.Func([TestCatalogInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBill' : IDL.Func([ReportId, IDL.Vec(BillLineItem)], [BillId], []),
    'createTestReport' : IDL.Func([TestReportInput], [ReportId], []),
    'getAllBillsByTimestamp' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getAllPatientsByCreatedAt' : IDL.Func(
        [],
        [IDL.Vec(PatientRecord)],
        ['query'],
      ),
    'getAllTestCatalog' : IDL.Func([], [IDL.Vec(Test)], ['query']),
    'getAllTestCatalogBySampleType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Test)],
        ['query'],
      ),
    'getBill' : IDL.Func([BillId], [Bill], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMostRecentPatients' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Patient)],
        ['query'],
      ),
    'getPatient' : IDL.Func([PatientId], [Patient], ['query']),
    'getPatientReportsByCreatedAt' : IDL.Func(
        [PatientId],
        [IDL.Vec(TestReport)],
        ['query'],
      ),
    'getReportsByStatus' : IDL.Func(
        [TestStatus],
        [IDL.Vec(TestReport)],
        ['query'],
      ),
    'getSignature' : IDL.Func([ReportId], [ExternalBlob], ['query']),
    'getTestCatalog' : IDL.Func([TestCode], [Test], ['query']),
    'getTestReport' : IDL.Func([ReportId], [TestReport], ['query']),
    'getTestReportsByCompletedAt' : IDL.Func(
        [],
        [IDL.Vec(TestReport)],
        ['query'],
      ),
    'getTestReportsByCreatedAt' : IDL.Func(
        [],
        [IDL.Vec(TestReport)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'storeSignature' : IDL.Func([ReportId, ExternalBlob], [], []),
    'updatePatient' : IDL.Func([PatientId, PatientInput], [], []),
    'updatePaymentStatus' : IDL.Func([BillId, PaymentStatus], [], []),
    'updateTestPrice' : IDL.Func([TestCode, IDL.Nat], [], []),
    'updateTestReportResult' : IDL.Func(
        [ReportId, IDL.Vec(TestResult)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };